const FILE_ICONS: Record<string, string> = {
  ts: 'typescript',
  tsx: 'react',
  js: 'javascript',
  jsx: 'react',
  py: 'python',
  rs: 'rust',
  go: 'golang',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  cpp: 'cpp',
  c: 'c',
  h: 'header',
  hpp: 'header',
  css: 'css',
  scss: 'sass',
  less: 'css',
  html: 'html',
  vue: 'vue',
  svelte: 'svelte',
  json: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  xml: 'xml',
  md: 'markdown',
  sql: 'sql',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  dockerfile: 'docker',
  toml: 'config',
  ini: 'config',
  cfg: 'config',
  lock: 'lock',
  gitignore: 'git',
  env: 'tune',
  svg: 'svg',
  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  gif: 'image',
  webp: 'image',
  ico: 'image',
  woff: 'font',
  woff2: 'font',
  ttf: 'font',
  eot: 'font',
  pdf: 'pdf',
  zip: 'archive',
  tar: 'archive',
  gz: 'archive',
  rar: 'archive',
  '7z': 'archive',
}

const FOLDER_ICONS: Record<string, string> = {
  src: 'src',
  dist: 'dist',
  build: 'dist',
  out: 'dist',
  node_modules: 'npm',
  '.git': 'git',
  components: 'react',
  pages: 'react',
  views: 'react',
  routes: 'react',
  api: 'api',
  public: 'public',
  assets: 'assets',
  images: 'image',
  img: 'image',
  icons: 'image',
  fonts: 'font',
  styles: 'css',
  css: 'css',
  tests: 'test',
  __tests__: 'test',
  test: 'test',
  spec: 'test',
  docs: 'docs',
  doc: 'docs',
  config: 'config',
  settings: 'config',
  scripts: 'script',
  utils: 'utility',
  helpers: 'utility',
  lib: 'lib',
  hooks: 'hook',
  context: 'context',
  store: 'store',
  state: 'store',
  types: 'types',
  interfaces: 'types',
  models: 'types',
  db: 'database',
  database: 'database',
  migrations: 'database',
  docker: 'docker',
  '.vscode': 'vscode',
  '.github': 'github',
  '.husky': 'husky',
}

const ICON_COLORS: Record<string, string> = {
  typescript: '#3178c6',
  javascript: '#f7df1e',
  react: '#61dafb',
  python: '#3776ab',
  rust: '#dea584',
  golang: '#00add8',
  java: '#b07219',
  kotlin: '#7f52ff',
  swift: '#f05138',
  cpp: '#00599c',
  c: '#a8b9cc',
  css: '#663399',
  sass: '#cc6699',
  html: '#e34f26',
  vue: '#4fc08d',
  svelte: '#ff3e00',
  json: '#5c5c5c',
  yaml: '#cb171e',
  markdown: '#083fa1',
  sql: '#e38c00',
  shell: '#89e051',
  docker: '#2496ed',
  git: '#f05032',
  npm: '#cb3837',
  svg: '#ffb13b',
  image: '#a074c4',
  font: '#4285f4',
  pdf: '#ec1c24',
  archive: '#c9a93e',
  config: '#8bc34a',
  test: '#4caf50',
  docs: '#2196f3',
  script: '#607d8b',
  lock: '#ffab00',
  tune: '#9c27b0',
}

export function fileIcon(name: string): { type: string; color: string } {
  const ext = name.split('.').pop()?.toLowerCase() || ''
  const iconType = FILE_ICONS[ext] || 'file'
  return { type: iconType, color: ICON_COLORS[iconType] || '#808080' }
}

export function folderIcon(name: string, expanded: boolean): { type: string; color: string } {
  const key = name.toLowerCase()
  const iconType = FOLDER_ICONS[key] || (expanded ? 'folder-open' : 'folder')
  return { type: iconType, color: ICON_COLORS[iconType] || '#dcb67a' }
}

export function gitStatusIcon(status: string): string {
  const map: Record<string, string> = {
    modified: 'M',
    added: 'A',
    deleted: 'D',
    renamed: 'R',
    untracked: 'U',
    ignored: 'I',
    staged: 'S',
  }
  return map[status] || ''
}
